### ISSUE TITLE
V3 is too slow as compared to V2

### ISSUE THREAD

**Issue by DeanJain** [memsql/memsql-spark-connector#60] opened 2020-10-22 00:20 UTC
we were using Spark connector V2 from quite some time and had it benchmarked, we recently tried using V3 connector and surprisingly its 2X-3X slower than V2:

**V2 :** 
```
<dependency>
    <groupId>com.memsql</groupId>
    <artifactId>memsql-connector_2.11</artifactId>
    <version>2.0.6</version>
</dependency>
```

**V3:**
```
<dependency>
    <groupId>com.memsql</groupId>
    <artifactId>memsql-spark-connector_2.11</artifactId>
    <version>3.0.4-spark-2.3.4</version>
</dependency>
```

Some stats:
Data Ingestion Size 300GB / 2.2 B records

RDD Partitions | Memsql Connector V2 Total Ingestion Time in minutes | Memsql Connector V3 Total ingestion time in mins | DB Partitions | Comment
-- | -- | -- | -- | --
32 | 135 | 190 | total 32 |  
32 | 65 | 175   |  total 32  |

Spark config used was same for both connectors.

```
spark.speculation=false
spark.driver.memory=30G
spark.executor.memory=25G
spark.executor.instances=32
spark.executor.cores=8
spark.yarn.maxAppAttempts=1
spark.memory.storageFraction=0.2
spark.memory.fraction=0.85
```

**Comment by carlsverre** [comment] 2020-10-22 00:27
@DeanJain thanks for the report!  Can you try using the latest version of our connector (3.0.5)?  We fixed a pretty big issue related to large scale ingest which may directly address this problem.  If that doesn't help can you:
* experiment with different compression settings
* confirm whether or not you are using the `on duplicate key` feature

Thanks!

**Comment by DeanJain** [comment] 2020-10-22 05:22
do you mean this fix [commit](https://github.com/memsql/memsql-spark-connector/commit/c74118dc05789d0229b2127f13a79c478effc012) ? 

its a different issue then load balancing, **even in V2 connector all the ingestion request are going to only one aggregator but its still 2-3X faster,** so even though this load balancing fix will help improve the performance, but still if you do apple to apple comparison then still there seems to be a bug in V3 which is giving it much slower performance.

**Comment by carlsverre** [comment] 2020-10-22 15:23
Thanks for the confirmation.  Can you provide an example of how you are writing data?  I assume you are using the same driver code to load data using each of the connector versions?  Also please provide details on the following questions:
* are you using the `on duplicate key` feature
* which compression setting are you using
* provide a list of all non-sensitive (i.e. password) memsql configuration variables for each of the driver versions

**Comment by DeanJain** [comment] 2020-10-22 21:34
yes its exactly same code / same driver on both v2 and v3. both uses same data writes: 

`dataset.write().format("memsql").mode("overwrite").save(tableName);`

- we are **not** using "on duplicate key"
- we are using default setting for compression

V2 Spark MemSQL config:

- memsql.host=xxx
- memsql.port=xxxx
- memsql.user=xxxx
- memsql.password=xxxx
- memsql.defaultDatabase=xxxx

V3 Spark MemSQL config:

- memsql.ddlEndpoint=host:port
- memsql.dmlEndpoint=MA,CA:port
- memsql.user=xxx
- memsql.password=xxxx
- memsql.defaultDatabase=xxx

**Comment by carlsverre** [comment] 2020-10-22 22:20
Thanks for the reply - we will investigate, repro, and get back to you soon.

**Comment by blinov-ivan** [comment] 2020-10-27 18:23
Hi @DeanJain,
we tested the performance of both v2 and v3 spark-connector and they became almost identical (+-1-2%).
Such a big difference may be caused by some misconfiguration.
How can we help you to resolve this issue?

Best Regards

**Comment by DeanJain** [comment] 2020-10-28 00:24
Thanks, The difference is visible when you test on high volume, 300GB+ 2-3 Billion records... did you tested and compared both with such high volume ?

**Comment by blinov-ivan** [comment] 2020-10-30 15:04
Hi, @DeanJain ,
we just finished testing with high volume (1B rows, 160GB) and here's the results:
`V3 - 18.60 minutes
V2 - 16.33 minutes`
Could you please provide some details of your test flow?
Are you reading data from some other source and trying to write it to memsql? Could you please provide all the details.
Thanks!

**Comment by DeanJain** [comment] 2020-11-02 04:20
Hey @blinov-ivan - both the V2 and V3 jobs have same code except connector dependency, both are reading data from Hive and loading into DataSet and then Saving to MemSQL.

let me know if you need any more / specific details, thanks

**Comment by blinov-ivan** [comment] 2020-11-02 15:55
@DeanJain we continued to test the performance and did not find anything similar to your results.
Currently, we have an assumption that the issue could be related to table indices. 
V2 by default creates a rowstore table but V3 creates columnstore table.
Could you please clarify how do you create the tables? Are you writing both to rowstore table?
And could you also provide the schema of your testing data?
Thanks!

**Comment by DeanJain** [comment] 2020-11-02 18:19
Both V2 and V3 Connectors writes to the same MemSQL Columnstore Table, The table is precreated and is an existing table on memSQL, Spark Connector is just loading data into this existing table its not creating it on the fly, schema is like below:

```
CREATE TABLE `xxxx_columnstore` (
  `xid` binary(18) NOT NULL,
.
. blah blah blah columns,
.
,
  KEY `keyxxx` (`c1`,`c2`,`c3`,`c4`)  USING CLUSTERED COLUMNSTORE,
  SHARD KEY `xid` (`xid`)
) 
```

**Comment by DeanJain** [comment] 2020-11-02 18:21
Both connectors are doing same operation:

dataset.write().format("memsql").mode("overwrite").save("xxxx_columnstore");

**Comment by carlsverre** [comment] 2020-11-02 19:32
@DeanJain can you send us the full table schema?  We just need all the types/indexes/shard keys/etc - don't care about the column names.

Thanks

**Comment by carlsverre** [comment] 2020-11-02 20:40
Oh it looks like we have your schema on file with our support team.  Will use that to try to reproduce your results.  Thanks

**Comment by blinov-ivan** [comment] 2020-11-02 22:42
@DeanJain sorry for taking so long,
but could you also provide the schema of the data frame you are loading, we ask for it because we assume you're loading into `binary(*)` field of MemSQL not `BinaryType` but some other Spark type. Is it correct?
Thanks

**Comment by DeanJain** [comment] 2020-11-02 23:13
All columns on Spark are DataTypes.StringType

**Comment by blinov-ivan** [comment] 2020-11-03 00:31
@DeanJain looks like that could be an issue.
If you are using mode `Overwrite` in V3 spark-connector, it will drop and recreate the table based on your dataFrame schema. In your case, it will create the table with only `text` fields type. Writing to such table is slower than to the schema you provided.
To resolve this issue you could:
1. Use `Append` mode instead of `Overwrite`. In this case you will add new rows instead of overriding them.
2. Use option `overwriteBehavior=merge`. like this:
`df.write
    .format("memsql")
    .mode(SaveMode.Overwrite)
    .option("overwriteBehavior", "merge")
    .save(s"database.table")`
Using this option, spark-connector won't drop and create the table, it will just replace old rows with new ones based on primary keys.
Could you please try this approaches?
Thanks!

**Comment by DeanJain** [comment] 2020-11-03 01:14
This is what the documentation says on your site: https://docs.singlestore.com/v7.1/third-party-integrations/spark-3-connector/

"SaveMode.Overwrite means that when saving a DataFrame to a data source, if data/table already exists, existing data is expected to be overwritten by the contents of the DataFrame."

it clearly says if table exists its going to overwrite... then this documentation needs to be fixed. or there is a bug in over write it should not drop and create if table exists, it should just update overwrite on existing table.

pls clarify...

**Comment by DeanJain** [comment] 2020-11-03 01:25
pls let me know which ones of below you want us to try:

1. // this is what we did at first place and it did not perform:
df.write
    .format("memsql")
    .mode(SaveMode.Overwrite)
    .option("overwriteBehavior", "truncate")
    .save("database.table")

2. 
df.write
    .format("memsql")
    .mode(SaveMode.Overwrite)
    .option("overwriteBehavior", "merge")
    .save("database.table")

3. 
df.write
    .format("memsql")
    .mode(SaveMode.Append)
    .save("database.table")

which ones you want us to retry 1/2/3 or all ?

**Comment by DeanJain** [comment] 2020-11-04 04:59
sure will do, thanks

**Comment by blinov-ivan** [comment] 2020-11-17 13:47
Hi @DeanJain, do you have any updates on your performance testing?

**Comment by blinov-ivan** [comment] 2020-11-20 13:35
@DeanJain we will close this issue as there is no answer.
Please reopen this ticket if you will have the same issue in the future.

Thanks!

**Closed** 2020-11-20 13:35 UTC

**Comment by DeanJain** [comment] 2020-11-20 21:24
Hey Guys, thanks for your help on this, we are busy with multiple major year end releases and will get this tested back again asap, will reopen once i have more details...

**Comment by DeanJain** [comment] 2020-11-24 23:17
@blinov-ivan - tried below option and getting this error, Do you guys know if we can make this work on a columnstore table with unique key ? any alternatives ?

df.write
.format("memsql")
.mode(SaveMode.Overwrite)
.option("overwriteBehavior", "merge")
.save("database.table")

```
java.sql.SQLException: (conn=1484366) Feature 'LOAD DATA REPLACE ON COLUMNAR TABLE WITH UNIQUE KEY INDEX' is not supported by MemSQL.
                at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:255)
                at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:165)
                at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:238)
                at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:356)
Caused by: java.sql.SQLException: Feature 'LOAD DATA REPLACE ON COLUMNAR TABLE WITH UNIQUE KEY INDEX' is not supported by MemSQL.
Query is: LOAD DATA LOCAL INFILE '###.gz' REPLACE INTO TABLE `abc_test` (`act_id`, `org_cd`) MAX_ERRORS 0
```

**Comment by blinov-ivan** [comment] 2020-11-25 17:22
@DeanJain seems like `REPLACE` doesn't work for columnar tables with a unique key in 7.1 version of SingleStore but it will be possible in 7.3 version.
Meanwhile, you can still try 
```
df.write
.format("memsql")
.mode(SaveMode.Append)
.save("database.table")
```
or if you will have duplicates in your table you can use `onDuplicateKeySQL` option.
You can read more about this option [here](https://github.com/memsql/memsql-spark-connector#inserting-rows-into-the-table-with-on-duplicate-key-update). The code should look similar to the below.
```
df.write
    .format("memsql")
    .option("onDuplicateKeySQL", "id = id")
    .mode(SaveMode.Overwrite)
    .save("database.table")
```

Hope it will work for you!

**Comment by DeanJain** [comment] 2021-01-14 18:25
thanks Team, here is a quick update... 

with below fixed version of V3, we did thorough resting and comparison with V2 connector and found below:

1. Data Load Performance was 10% faster than V2
2. Aggregator load balancing was working with this new fixed version, V2 doesnt has this feature.


```
<dependency>
                <groupId>com.memsql</groupId>
                <artifactId>memsql-spark-connector_2.11</artifactId>
                <version>3.0.5-spark-2.4.4</version>
            </dependency>
```

**Comment by carlsverre** [comment] 2021-01-14 18:34
So before I celebrate too much it sounds like the issues you had from before are resolved **and** you have found some improvements from the V2 connector?  That's fantastic!  Thanks for letting us know!

**Comment by DeanJain** [comment] 2021-01-14 18:43
Ohh YEAH time to celebrate, we are moving to production with this new fixed V3 connector, things definitely looks much better... thanks again for all your continued support ! @carlsverre @blinov-ivan
